trigger:
  branches:
    include:
      - Dev

pr: none

pool:
  vmImage: "windows-latest"

variables:
  nodeVersion: "22.x"
  appServiceName: "HORKOS-FRONT-DEV-AS"
  azureSubscription: "Azure Dev (eb9ca34c-212d-4020-98f1-d7f3430ae2ce)"
  resourceGroup: "PISTIS-DEV"
  app_location: "pistis"
  output_location: "pistis/dist"

stages:

  - stage: Build
    displayName: "Build Vue.js App"
    jobs:
      - job: Build
        displayName: "Build Job"

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
              checkLatest: true

          - powershell: |
              echo "Building Vue.js"
              cd $(app_location)
              npm ci
              npm run build:staging
            displayName: "Install deps & build Vue"

          - task: CopyFiles@2
            displayName: "Copy web.config to dist"
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)/$(app_location)"
              Contents: |
                **/web.config
              TargetFolder: "$(Build.SourcesDirectory)/$(output_location)"

          - script: |
              echo "=== dist folder structure ==="
              dir "$(Build.SourcesDirectory)/$(output_location)" /s
            displayName: "DEBUG dist"

          - task: ArchiveFiles@2
            displayName: "Create deployable ZIP"
            inputs:
              rootFolderOrFile: "$(Build.SourcesDirectory)/$(output_location)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)/app.zip"
              artifactName: "pistisdist"
              publishLocation: Container


  - stage: Deploy
    displayName: "Deploy to Azure App Service"
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: "Deploy Job"
        environment: "dev"

        strategy:
          runOnce:
            deploy:
              steps:

                - download: current
                  artifact: pistisdist

                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: "$(Pipeline.Workspace)/pistisdist/app.zip"
                    destinationFolder: "$(Pipeline.Workspace)/pistisdist_unzipped"
                - script: |
                    echo "=== ZIP content ==="
                    dir "$(Pipeline.Workspace)/pistisdist_unzipped" /s
                  displayName: "DEBUG ZIP content"

                - task: AzureWebApp@1
                  displayName: "Deploy to Azure Web App"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: "webApp"
                    appName: $(appServiceName)
                    package: "$(Pipeline.Workspace)/pistisdist/app.zip"
