export enum FactTag {
  PublicIdentity = 'Identité publique',
  Career = 'Carrière',
  PastCase = 'Affaires passées',
  BelongingsDeclaration = 'Déclaration de patrimoine',
  Scandale = 'Scandale',
  RulesRespect = 'Respect des règles',
  InterestConflict = 'Conflit d’intérêts',
  Promises = 'Promesses',
  Stability = 'Stabilité',
  Consistency = 'Cohérence',
  TangibleResult = 'Résultats concrets',
  Communication = 'Communication',
  RelationShip = 'Relations',
  Independancy = 'Indépendance',
  PublicAttitude = 'Attitude publique',
  EthicalBehavior = 'Comportement éthique',
  Management = 'Gestion',
}
